### ISSUE TITLE
versionCode missing in APK

### ISSUE THREAD

**Issue by IzzySoft** [unitools-apps/UniTools-android#4]
The APK attached to `releases/` lacks a versionCode:

```
CRITICAL: Package matching failed: invalid literal for int() with base 10: ''
Line was: package: name='com.github.ali77gh.unitools' versionCode='' versionName='1.5.0' platformBuildVersionName='1.5.0'
```

As Android uses this field to determine the version (and potential updates), you should make sure it's there :wink:

**Comment by ali77gh** [comment]
hi. 
first of all i'm so happy to see you are using this app from Germany if you are interested you can help to add Germany language to this app. all you have to do is make a .xml file like [this](https://github.com/unitools-apps/UniTools-android/blob/master/app/src/main/res/values/strings.xml) (in germany) and make pull request.

and about the issue :
i just put "versionCode" [here](https://github.com/unitools-apps/UniTools-android/blob/master/app/build.gradle) and I have no idea why its not working on your phone and I have no problem in updating app.
but i recommend you to download and install app from [here](https://github.com/unitools-apps/UniTools-android/releases/download/1.7.0/unitools-1.7.0.4.apk).

anyway if you solved problem tell me.
good luck ;)

**Comment by IzzySoft** [comment]
I can confirm the latest release no longer has that issue, thanks! And no, I'm not using the app myself – I just [spread the word](https://apt.izzysoft.de/fdroid/index/apk/com.github.ali77gh.unitools) :smiley: You're welcome linking there: that repository allows to use the [F-Droid](https://f-droid.org/) app to install UniTools and automatically keep it up-to-date. New versions get available within 24h of your tagging and attaching the APK here.

Btw: are there any English screenshots available? I then could include them (currently, screenshots are shown in the F-Droid app only, my web frontend doesn't yet support them).

As the problem has been solved, I'm closing this issue now. Thanks again!

PS: If you want to have your app included with the official F-Droid repo, just let me know if I shall assist you with that.

**Comment by ali77gh** [comment]
hi.
I just translate README.md to English and English screenshots are now available.
sure. 
so when I release new version in github it will updates automatically in f-droid?
that sound cool :smiley:

**Comment by IzzySoft** [comment]
Aww, another Github notification that got lost… No, in my repo only the APK is updated automatically. But you can always ping me if description or screenshots need to be updated.

I've just made a note to add the screenshots when I'm back home tonight. If you'd use Fastlane structures for that (see e.g. [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) for details), you could even use that for deployment to Play Store – and if you one day decide to get your app into the official F-Droid repo, those details would be pulled automatically.
