### ISSUE TITLE
Better English translations

### ISSUE THREAD

**Issue by JustMeErazem** [unitools-apps/UniTools-android#6]
Some English translations are lacking or not properly translated.

**Comment by ali77gh** [comment]
hello again.

you can make pull request for [this file](https://github.com/unitools-apps/UniTools-android/blob/master/app/src/main/res/values/strings.xml) and fix whatever you think is lacking or not properly translated.

**example:**
~~~xml
<-- before --!>
<string name="tools">tools</string>
<-- after --!>
<string name="tools">edited to whatever you want</string>

<-- so don't touch name attribute --!>
~~~

I will be so happy :smiley:  if you do this
