### ISSUE TITLE
Force close when swithing to PDF tab with one PDF added

### ISSUE THREAD

**Issue by JustMeErazem** [unitools-apps/UniTools-android#8]
After I added a PDF to the PDF section and try to view it I got a force close.

Screenshot: https://ibb.co/NY7GVgX

Debug log: https://del.dog/tufomiroxo

**Comment by ali77gh** [comment]
hello again.
thanks for helping this project.
first of all which android version you are using?

anyway I think I solved it. try [this apk](https://nofile.io/f/uN4mXKeKABq/app-debug.apk) file

**Comment by JustMeErazem** [comment]
Don't remember which version I was on before, but the one you sent solved it, thanks :)

**Comment by ali77gh** [comment]
then it will be fixed in next release
thanks again
